<<<<<<< HEAD
# Generated by Django 2.2.1 on 2020-01-06 14:52
=======
# Generated by Django 2.1.5 on 2020-01-04 06:29
>>>>>>> dc0c6dc85e2a0298c9b1674de22c6c130ffb3b26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
>>>>>>> dc0c6dc85e2a0298c9b1674de22c6c130ffb3b26
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('owner', models.CharField(default='???', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('body', models.TextField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='freeboard.Post')),
            ],
=======
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='freeboard.Post'),
>>>>>>> dc0c6dc85e2a0298c9b1674de22c6c130ffb3b26
        ),
    ]
