# Generated by Django 2.2.1 on 2020-01-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200107_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='choose_people',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
