# Generated by Django 2.2.1 on 2020-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_choose_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='choose_people',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
