# Generated by Django 2.2.1 on 2020-01-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='blog/profile_pic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='blog/%Y/%m/%d'),
        ),
    ]
